name = "QuantumControl"
uuid = "8a270532-f23f-47a8-83a9-b33d10cad486"
authors = ["Michael Goerz <mail@michaelgoerz.net>", "Alastair Marshall <alastair@nvision-imaging.com>"]
version = "0.0.3+dev"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
QuantumPropagators = "7bf12567-5742-4b91-a078-644e72a65fc1"
QuantumControlBase = "f10a33bc-5a64-497c-be7b-6f86b4f0c2aa"
Krotov = "b05dcdc7-62f6-4360-bf2c-0898bba419de"
GRAPE = "6b52fcaf-80fe-489a-93e9-9f92080510be"

[compat]
GRAPE = "0.0.2"
Krotov = "0.0.3"
QuantumControlBase = "0.0.3"
QuantumPropagators = "0.0.3"
julia = "1.6"
