name = "QuantumControl"
uuid = "8a270532-f23f-47a8-83a9-b33d10cad486"
authors = ["Michael Goerz <mail@michaelgoerz.net>", "Alastair Marshall <alastair@nvision-imaging.com>", "and contributors"]
version = "0.0.1"

[deps]
QuantumControlBase = "f10a33bc-5a64-497c-be7b-6f86b4f0c2aa"

[compat]
julia = "1.6"
QuantumControlBase = "^0"


[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
