name: CI-release
on:
  push:
    branches:
      - 'release-*'
env:
  GKSwstype: 100
  JULIA_PKG_PRECOMPILE_AUTO: false
jobs:
  test:
    name: Test for Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/cache@v1
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1
      - run: |
          # Set up registries
          julia --project=@. -e '
            using Pkg
            println("Set up registries")
            Pkg.Registry.add(RegistrySpec(url="https://github.com/JuliaRegistries/General.git"))
            Pkg.Registry.add(RegistrySpec(url="https://github.com/JuliaQuantumControl/QuantumControlRegistry.git"))'
      - run: |
          # Install dev-version of QuantumControlTestUtils
          julia --project=@. --threads auto -e '
            using Pkg
            Pkg.activate(".")
            Pkg.develop("QuantumControlTestUtils")'
      - run: |
          # Run downstream "QuantumControlBase" tests
          julia --project=@. --threads auto -e '
            using Pkg
            Pkg.activate(".")
            Pkg.test("QuantumControlBase")'
      - run: |
          # Run downstream "QuantumPropagators" tests
          julia --project=@. --threads auto -e '
            using Pkg
            Pkg.activate(".")
            Pkg.test("QuantumPropagators")'
      - run: |
          # Run downstream "Krotov" tests
          julia --project=@. --threads auto -e '
            using Pkg
            Pkg.activate(".")
            Pkg.test("Krotov")'
      - run: |
          # Run downstream "GRAPE" tests
          julia --project=@. --threads auto -e '
            using Pkg
            Pkg.activate(".")
            Pkg.test("GRAPE")'
      - run: |
          # Run tests
          julia --project=@. -e '
            using Pkg
            Pkg.activate(".")
            Pkg.test()'
